variable "REQUESTER_AWS_ACCESS_KEY_ID" {}
variable "REQUESTER_AWS_SECRET_ACCESS_KEY" {}
variable "REQUESTER_AWS_REGION" {}

variable "ACCEPTER_AWS_ACCESS_KEY_ID" {}
variable "ACCEPTER_AWS_SECRET_ACCESS_KEY" {}
variable "ACCEPTER_AWS_REGION" {}
